import { mkdir, readFile, writeFile } from 'node:fs/promises';

const sourceUrl = process.env.GITHUB_PROFILE_README_URL
  || 'https://raw.githubusercontent.com/Lakmal2078/Lakmal2078/main/README.md';
const outputPath = process.env.PROFILE_OUTPUT || new URL('../src/profile-data.js', import.meta.url);

const fallback = {
  name: 'Lakmal Vidana Gamage',
  username: 'Lakmal2078',
  role: 'Android · Web · Backend Developer',
  bio: 'A developer from Sri Lanka building practical, reliable and user-focused digital products.',
  sinhalaBio: 'සැබෑ ගැටලු සඳහා වේගවත්, ආරක්ෂිත සහ භාවිතයට පහසු digital solutions නිර්මාණය කරමු.',
  tags: ['KOTLIN', 'REACT', 'PYTHON', 'FIREBASE'],
  focus: [
    { title: 'Android Apps', detail: 'Mobile experiences' },
    { title: 'Modern Web', detail: 'Clean interfaces' },
    { title: 'Backend & APIs', detail: 'Reliable systems' },
    { title: 'Automation', detail: 'Smarter workflows' }
  ],
  sourceUrl: 'https://github.com/Lakmal2078/Lakmal2078',
  syncedAt: null
};

function section(markdown, heading) {
  const match = markdown.match(new RegExp(`^##\\s+[^\\n]*${heading}[^\\n]*\\n([\\s\\S]*?)(?=^##\\s|$)`, 'im'));
  return match?.[1]?.trim() || '';
}

function clean(value) {
  return value.replace(/<[^>]+>/g, ' ').replace(/[*_`#]/g, '').replace(/\\s+/g, ' ').trim();
}

function firstParagraph(text, languageHeading) {
  const withoutHeading = text.replace(new RegExp(`^###\\s+[^\\n]*${languageHeading}[^\\n]*\\n?`, 'im'), '');
  return clean(withoutHeading.split(/\\n\\s*\\n/)[0] || '');
}

function parseProfile(markdown) {
  const about = section(markdown, 'About Me|මා ගැන');
  const building = section(markdown, "What I'm Building|මම ගොඩනඟන දේවල්");
  const stack = section(markdown, 'Tech Stack|මගේ තාක්ෂණික හැකියාවන්');
  const nameMatch = markdown.match(/(?:Hi|Hello|I'm|I am)[^\\n]*?([A-Z][a-z]+(?:\\s+[A-Z][a-z]+){1,3})/);
  const focusItems = [...building.matchAll(/^[-*]\\s+(?:[^A-Za-z\\n]*)([^\\n]+)/gim)]
    .map((match) => clean(match[1]))
    .filter(Boolean)
    .slice(0, 4);
  const tagCandidates = ['Kotlin', 'React', 'Python', 'Firebase', 'JavaScript', 'Node.js', 'Android'];
  const tags = tagCandidates.filter((tag) => new RegExp(`\\b${tag.replace('.', '\\.') }\\b`, 'i').test(stack));
  const parsed = {
    ...fallback,
    name: nameMatch?.[1] || fallback.name,
    bio: firstParagraph(about, 'English') || fallback.bio,
    sinhalaBio: firstParagraph(about, 'සිංහල') || fallback.sinhalaBio,
    tags: tags.length >= 3 ? tags.slice(0, 4).map((tag) => tag.toUpperCase()) : fallback.tags,
    focus: focusItems.length >= 2
      ? focusItems.map((title, index) => ({ title, detail: fallback.focus[index]?.detail || 'Digital solutions' }))
      : fallback.focus,
    // Keep generated output stable when the source README has not changed.
    syncedAt: fallback.syncedAt
  };
  return parsed;
}

function moduleText(profile) {
  return `// Generated by scripts/sync-profile.mjs. Do not edit manually.\nexport const profile = ${JSON.stringify(profile, null, 2)};\n`;
}

const response = await fetch(sourceUrl, { headers: { 'User-Agent': 'Growhand-profile-sync' } });
if (!response.ok) throw new Error(`Could not fetch profile README (${response.status} ${response.statusText})`);
const markdown = await response.text();
if (markdown.length < 100) throw new Error('Profile README looks unexpectedly short; refusing to overwrite synced data.');
await mkdir(new URL('../src/', import.meta.url), { recursive: true });
await writeFile(outputPath, moduleText(parseProfile(markdown)));
console.log(`Synced GitHub profile README → ${outputPath.pathname || outputPath}`);
