// Generated by scripts/sync-profile.mjs. Do not edit manually.
export const profile = {
  "name": "Lakmal Vidana Gamage",
  "username": "Lakmal2078",
  "role": "Android · Web · Backend Developer",
  "bio": "A developer from Sri Lanka building practical, reliable and user-focused digital products.",
  "sinhalaBio": "සැබෑ ගැටලු සඳහා වේගවත්, ආරක්ෂිත සහ භාවිතයට පහසු digital solutions නිර්මාණය කරමු.",
  "tags": [
    "KOTLIN",
    "REACT",
    "PYTHON",
    "FIREBASE"
  ],
  "focus": [
    {
      "title": "Android Apps",
      "detail": "Mobile experiences"
    },
    {
      "title": "Modern Web",
      "detail": "Clean interfaces"
    },
    {
      "title": "Backend & APIs",
      "detail": "Reliable systems"
    },
    {
      "title": "Automation",
      "detail": "Smarter workflows"
    }
  ],
  "sourceUrl": "https://github.com/Lakmal2078/Lakmal2078",
  "syncedAt": null
};
